### ISSUE TITLE
Crash on placing ceramic hive in multiplayer

### ISSUE THREAD

**Issue by NovaNine** [VinterNacht/FromGoldenCombs#11]
When anyone on our server places down a ceramic hive (confirmed on top of fence pole and on top of packed dirt), the game of **everyone else** on the server crashes (but not the person placing it).

We did not confirm if there is a max radius to this, but it definitely happens within 200 blocks or so.  This is a client-only crash and the dedicated server continues just fine.

Here's the error:

```
Running on 64 bit Windows with 0 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: ancienttools@1.4.0, betterdrifters@2.1.3, dragonflies@1.1.8, peifme@1.0.0, primitivesurvival@2.8.0, viescraftmachines@1.9.0, game@1.16.4, vshud@2.0.31, alchemy@1.6.0, carrycapacity@0.6.5, farmlife@1.2.3, fromgoldencombs@1.3.6-rc.5, hudclock@2.7.0, lichen@1.6.1, medievalexpansion@3.7.1, petai@1.3.6, peifm@1.0.2, playercorpse@1.3.1, prospectorinfo@3.1.2, stepup@1.2.0, creative@1.16.4, survival@1.16.4, campaigncartographer@2.1.2, cats@1.3.4, packanimals@1.0.0, wildcraft@1.2.1
3/13/2022 7:45:11 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at FromGoldenCombs.Blocks.CeramicBroodPot.OnBlockPlaced(IWorldAccessor world, BlockPos blockPos, ItemStack byItemStack)
   at Vintagestory.Common.BlockAccessorRelaxed.SetBlock_Patch2(BlockAccessorRelaxed this, Int32 blockId, BlockPos pos, ItemStack byItemstack)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSetBlock(_zqyp7oNseOe29EJgSPWAkirfxhw packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _4Bi1AGVssrIO0El8b8ygdS9FIfm._o5h005s1ovnxSPPqKWgI4tZUoCh(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/13/2022 2:13:57 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1932823765277171328, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 6219e03d
P4: KERNELBASE.dll
P5: 10.0.19041.1466
P6: e01c7650
P7: c0020001
P8: 0000000000034f69
P9: 
P10: 

Attached files:
\\?\C:\Users\Alex\AppData\Local\Temp\WER8B4B.tmp.WERDataCollectionStatus.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B0C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B1C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B29.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B59.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_38e6124c2f5079c7624a4e82674ca728f7cad76c_81245bb0_aa7b550f-7723-4f2d-89e3-0da4f67a40ca

Analysis symbol: 
Rechecking for solution: 0
Report Id: 22e4a763-4cc0-4091-8020-89afda9fd0dd
Report Status: 268566528
Hashed bucket: 0327dce96b38deb91ad2c4f956c75e80
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/13/2022 2:13:52 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.16.4.0, time stamp: 0x6219e03d
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1466, time stamp: 0xe01c7650
Exception code: 0xc0020001
Fault offset: 0x0000000000034f69
Faulting process id: 0x11f8
Faulting application start time: 0x01d836fbe660807e
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 22e4a763-4cc0-4091-8020-89afda9fd0dd
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 3/13/2022 2:13:50 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FF89BCE4F69
Stack:
 }
```

**Comment by VinterNacht** [comment]
You need to upgrade your version.  You're using a 1.15 version.

**Comment by NovaNine** [comment]
Of the mod?  We're using mod version 1.6.0 which according to [this page](https://mods.vintagestory.at/show/mod/487) is for 1.16.4 game and was uploaded March 4th.  I downloaded it March 7th.

Both the server and client have this 1.6.0 file.

The client displays "1.16.4 (Stable)" in the bottom right of the menu screen and the server identifies itself as v1.16.4 (Stable) in the console on startup.

**Comment by NovaNine** [comment]
Sorry, got my mods mixed in my first reply.  Will update to v1.3.6-rc.6

**Comment by VinterNacht** [comment]
My apologies, I was mistaken.  I wasn't at my computer at the time and misread the versioning number.  I'm not certain the update will solve this particular issue.  However, it's also the first time I've heard of this issue, so I'm intrigued.  Let me know if it happens again?

**Comment by VinterNacht** [comment]
Ok, the update isn't going to fix your concern either.  Going to take a look and see if I can find the source of the crash.

**Comment by NovaNine** [comment]
We updated to the rc.6 and confirmed it still happens.

**Comment by VinterNacht** [comment]
I have an odd request.  Can you attempt to place the Particulator from Primitive Survival and see if you get the same result?

**Comment by VinterNacht** [comment]
One last comment. NovaNine, have you still been experiencing concerns?

**Comment by NovaNine** [comment]
This is still happening and we just confirmed it happens with the Particulator:

https://i.imgur.com/U6VDp6V.jpeg

I got this from the player who crashed when placing the Particulator.  We momentarily switched to creative when we tested this as we did not have the materials for one in survival.

```
Loaded Mods: ancienttools@1.4.0, betterdrifters@2.1.3, dragonflies@1.1.8, peifme@1.0.0, primitivesurvival@2.8.0, viescraftmachines@1.9.0, game@1.16.4, alchemy@1.6.0, carrycapacity@0.6.5, farmlife@1.2.3, fromgoldencombs@1.3.6-rc.6, lichen@1.6.1, medievalexpansion@3.7.1, petai@1.3.6, peifm@1.0.2, playercorpse@1.3.1, creative@1.16.4, survival@1.16.4, cats@1.3.4, packanimals@1.0.0, wildcraft@1.2.1
3/19/2022 8:46:34 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at PrimitiveSurvival.ModSystem.BEParticulator.OnBlockPlaced(ItemStack byItemStack)
   at Vintagestory.Client.NoObf.ClientWorldMap.SpawnBlockEntity(String classname, BlockPos position, ItemStack byItemStack)
   at Vintagestory.API.Common.Block.OnBlockPlaced(IWorldAccessor world, BlockPos blockPos, ItemStack byItemStack)
   at PrimitiveSurvival.ModSystem.BlockParticulator.OnBlockPlaced(IWorldAccessor world, BlockPos pos, ItemStack stack)
   at Vintagestory.Common.BlockAccessorRelaxed.SetBlock(Int32 blockId, BlockPos pos, ItemStack byItemstack)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSetBlock(_zqyp7oNseOe29EJgSPWAkirfxhw packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _4Bi1AGVssrIO0El8b8ygdS9FIfm._o5h005s1ovnxSPPqKWgI4tZUoCh(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
   -------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/9/2022 9:21:05 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1404892564174130458, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\?\C:\Users\KT\AppData\Local\Temp\RDR9AC.tmp\empty.txt
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9BD.tmp.WERInternalMetadata.xml
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9CD.tmp.xml
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9DB.tmp.csv
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9FB.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: ef29eaba-60f3-41e8-80b1-e5cb9fb323bd
Report Status: 268435456
Hashed bucket: 7bdc35654b5a35c0737f2e57fb2fcd1a
Cab Guid: 0 }
```

**Comment by VinterNacht** [comment]
Latest release appears to resolve this issue.
